name: Branch clone
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs: 
  runs-on: ubuntu-latest
  steps:
  uses: peterjgrainger/action-create-branch@v2.2.0
    env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
    branch: 'release-notes'
    
